### ISSUE TITLE
Can't create accounts - Contract helper is not being initialized

### ISSUE THREAD

**Issue by CSFM93** [kurtosis-tech/near-kurtosis-lambda#87] opened 2022-11-11 05:16 UTC
Can't create new accounts after the recent update. I suspect that the contract helper container isn't being initialized since the command `docker ps` does not show the container running on port 8330.

Here is what `docker ps` returns :

![Screenshot from 2022-11-11 07-12-25](https://user-images.githubusercontent.com/48108095/201268467-6cd35883-47e0-4abe-bc27-ff4bc0dd23d8.png)

**Comment by gbouv** [comment] 2022-11-14 09:19
Hey @CSFM93 

Thank you for filing! I'm having an issue as well with the contract helper. It fails on startup with the following error:
```
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'aws-sdk/clients/dynamodb'
Require stack:
- /app/local_dynamo.js
- /app/scripts/create-dynamodb-tables.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/app/local_dynamo.js:1:28)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/local_dynamo.js', '/app/scripts/create-dynamodb-tables.js' ]
}
```
Can you confirm you're seeing the same? (running `docker ps -a` will show the exited container as well, and then you can get its logs with `docker logs`).

This error is unfortunately independent of Kurtosis as this script is part of the contract helper. I just opened [this issue](https://github.com/near/near-contract-helper/issues/656) on NEAR. As soon as it gets resolved, I'll update our module and cut a new version

**Comment by gbouv** [comment] 2022-11-14 09:41
Oh no the issue is on me actually. I'll fix it today and revert back to you when things are working @CSFM93

**Comment by mrostamii** [comment] 2022-11-15 07:02
I exactly have the same problem:
```
========================================== User Services ==========================================
GUID                                   ID                          Ports                                   Status
contract-helper-db-1668494013          contract-helper-db          postgres: 5432/tcp -> 127.0.0.1:49194   RUNNING
contract-helper-dynamo-db-1668494016   contract-helper-dynamo-db   default: 8000/tcp -> 127.0.0.1:49195    RUNNING
contract-helper-service-1668494020     contract-helper-service     rest: 3000/tcp                          STOPPED
explorer-backend-1668494021            explorer-backend            http: 8080/tcp -> 127.0.0.1:49196       RUNNING
explorer-frontend-1668494023           explorer-frontend           http: 3000/tcp -> 127.0.0.1:8331        RUNNING
indexer-node-1668494017                indexer-node                gossip: 24567/tcp -> 127.0.0.1:8333     RUNNING
                                                                   rpc: 3030/tcp -> 127.0.0.1:8332         
wallet-1668494024                      wallet                      http: 3004/tcp -> 127.0.0.1:8334        RUNNING
```

**Comment by gbouv** [comment] 2022-11-15 09:00
Yes still working on this, sorry for the inconvenience, we should have an update for later in the day

**Comment by WindowsHyun** [comment] 2022-11-15 09:55
![image](https://user-images.githubusercontent.com/7427841/201888830-61bb6226-0f8a-49d7-9de1-41f70e36ae31.png)
Same problem occurred.
May I know when will it be resolved?

**Comment by gbouv** [comment] 2022-11-15 14:55
I can confirm this is fixed now.

Please make sure you remove the `kurtosistech/near-contract-helper:88585e9` from your local docker such that docker re-downloads it, and then you can run:
```sh
kurtosis module exec 'kurtosistech/near-kurtosis-module:0.5.32'
```
It should start a working NEAR environment.

**Closed as completed by gbouv** 2022-11-15 14:55 UTC
